apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: github-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository URL
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: aro-dotnet-builder-github-pipelinerun-
      spec:
        pipelineRef:
          name: aro-dotnet-builder-pipeline
        resources:
          - name: git-source
            resourceSpec:
              type: git
              params:
                - name: url
                  value: $(params.gitrepositoryurl)
                - name: revision
                  value: $(params.gitrevision)
