apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-eventlistener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-trigger
      interceptors:
        - ref:
            name: "github"
          params:
            - name: secretRef
              value:
                secretKey: secretToken
                secretName: webhook-secret
      bindings:
        - ref: github-binding
      template:
        ref: github-template
